language: python
sudo: required
services: 
  - docker
  - postgresql

script:
  - docker-compose up run web python manage.py test

deploy:
  provider: script
  script: docker_push.sh
  on:
    branch: master