language: python
sudo: required
services: 
  - docker

install:
    - pip install -r requirements.txt
script:
    - docker-compose run web python manage.py test

deploy:
  provider: script
  script: docker_push.sh
  on:
    branch: master