sudo: required
services: 
  - docker
  - postgresql

install:
  - pip install -r requirements.txt

script:
  - docker-compose up run web python manage.py test

deploy:
  provider: script
  script: docker_push.sh
  on:
    branch: master