version: "3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=fitshop
      - POSTGRES_USER=fituser
      - POSTGRES_PASSWORD=fitpass
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    
