# Generated by Django 3.2.6 on 2021-08-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210820_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
