# Generated by Django 3.2.6 on 2021-10-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orderitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=0, help_text='100 = 1EUR', null=True),
        ),
    ]
