# Generated by Django 3.2.6 on 2021-08-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='amount',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='amount_currency',
            new_name='price_currency',
        ),
    ]
