# Generated by Django 3.2.6 on 2021-08-25 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210825_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.item'),
        ),
    ]
