# Generated by Django 3.2.6 on 2021-08-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210827_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_item',
            field=models.ManyToManyField(to='shop.Item'),
        ),
    ]
