# Generated by Django 3.2.6 on 2021-08-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_item_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='views',
            new_name='visits',
        ),
    ]
